name: Build Indev Version

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: '17'
            - name: Build with Gradle
              uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
              with:
                  arguments: build
            - name: Prepare for Artifact Upload
              run: |
                  mv build/libs/enhancedweather*.jar build/libs/enhancedweather-INDEV-$(echo ${{ github.sha }} | head --bytes=16).jar
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: EnhancedWeather-INDEV
                  path: build/libs/enhancedweather-INDEV-*.jar